### PR TITLE
Add polar to list of supported languages

### PR DESCRIPTION
**Pull request by vkarpov15**
Hi,

[Oso](https://www.osohq.com/) makes heavy use of codehike in their [Oso Cloud docs](https://www.osohq.com/docs/guides/role-based-access-control-rbac/roles), but right now they have to use ruby highlighting as a substitute for Polar, which is their language for modeling authorization rules. I got Polar syntax highlighting working with a [slightly hacky postinstall script](https://github.com/code-hike/codehike/issues/297#issuecomment-2223116250), but it would be very helpful if codehike could support Polar syntax highlighting natively.

The `polar.tmLanguage.json` in this PR is copied from this repo: https://github.com/osohq/polar-grammar

### CODE REVIEW

**Comment by pomber** [comment]
hey

I will start using the grammars from https://github.com/shikijs/textmate-grammars-themes, maybe you can add it there.

I'll also add the option for custom grammars in codehike v1

**Comment by vkarpov15** [comment]
Is there any way you can merge this in the v0.x release series? Custom grammars will be great when they're released and I'll switch to using that, but this change would be helpful for us in the interim.

**Comment by vkarpov15** [comment]
Thank you very much 🫶

**Comment by pomber** [comment]
there wont be a new release for @code-hike/mdx, but you can probably force the new version of @code-hike/lighter

**Comment by pomber** [comment]
or migrate to codehike v1, but that's more work

**Pull request merged**
